# Generated by Django 2.0.6 on 2018-08-01 18:08

from dateutil import tz
from django.db import migrations
from django.utils import timezone

def fix_timezone_error(apps, schema_editor):
    PhysData = apps.get_model('viz_app', 'PhysData')
    for line in PhysData.objects.all():
        bad_date = line.date
        naive_date = timezone.make_naive(bad_date, tz.gettz('EST'))
        utc_date = timezone.make_aware(naive_date, tz.gettz('UTC'))
        good_date = timezone.localtime(utc_date, tz.gettz('EST'))
        line.date = good_date
        line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0008_auto_20180723_2203'),
    ]

    operations = [
        migrations.RunPython(fix_timezone_error)
    ]
